project_name: NengoOCL
pkg_name: nengo_ocl
repo_name: nengo-labs/nengo-ocl
description: OpenCL-based simulator for Nengo neural models

copyright_start: 2013

contributing_rst: {}

license_rst: {}

manifest_in:
  recursive-include:
    - examples *.py

pyproject_toml: {}

pre_commit_config_yaml: {}

docs_conf_py:
  nengo_logo: nengo-ocl-full-light.svg
  nengo_logo_color: "#69c530"
  intersphinx_mapping:
    pyopencl: https://documen.tician.de/pyopencl/
    scipy: https://docs.scipy.org/doc/scipy/reference/

setup_py:
  url: https://labs.nengo.ai/nengo-ocl/
  include_package_data: True
  python_requires: ">=3.5"
  install_req:
    - nengo>=3.0.0,<3.1.0
    - mako
    - pyopencl
  docs_req:
    - matplotlib>=1.4
    - nbsphinx
    - nengo-sphinx-theme>=1.2.0
    - numpydoc>=0.6.0
    - sphinx>=1.8
  tests_req:
    - matplotlib>=1.4
    - pytest>=3.6.0
    - pytest-allclose>=1.0.0
    - pytest-plt>=1.0.0
    - pytest-rng>=1.0.0
  entry_points:
    nengo.backends:
      - ocl = nengo_ocl:Simulator
  classifiers:
      - "Development Status :: 5 - Production/Stable"
      - "Framework :: Nengo"
      - "Intended Audience :: Science/Research"
      - "License :: Free for non-commercial use"
      - "Operating System :: OS Independent"
      - "Programming Language :: Python"
      - "Programming Language :: Python :: 3.5"
      - "Programming Language :: Python :: 3.6"
      - "Programming Language :: Python :: 3.7"
      - "Topic :: Scientific/Engineering"
      - "Topic :: Scientific/Engineering :: Artificial Intelligence"
